version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: vitameet-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: vitameet
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build: VitaMeet-backend
    container_name: vitameet-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - vitameet-network

volumes:
  mysql-data:

networks:
  vitameet-network:
